# =============================================================================
# WORKFLOW TEMPLATE: Default (Standard Development)
# =============================================================================
#
# This is a TEMPLATE file for reference. Built-in workflows are not selectable
# in the workflow dropdown - only custom workflows appear there.
#
# TO USE THIS TEMPLATE:
# ---------------------
# 1. Copy this file to your project's .lanes/workflows/ directory
# 2. Customize the workflow for your project's needs
# 3. The workflow will appear in the "Custom" section of the dropdown
#
# AGENTS
# ------
# Agent names used in this workflow (in the `agents:` section and `agent:`
# fields on steps) must match agent definition files in your project's
# .claude/agents/ directory. For example:
#   - `agent: coder` requires .claude/agents/coder.md
#   - `agent: test-engineer` requires .claude/agents/test-engineer.md
#   - `agent: code-reviewer` requires .claude/agents/code-reviewer.md
#
# You can define agents inline in this file (as shown below) or reference
# external agent files. Inline definitions take precedence.
#
# OPTIONAL AGENT FIELD
# --------------------
# The `agent:` field on steps and sub-steps is OPTIONAL. If you omit it,
# the main Claude agent will handle that step directly instead of delegating
# to a specialized sub-agent. This is useful for simpler workflows or steps
# that don't require specialized capabilities.
#
# Example without agent (main Claude handles it):
#   - id: plan
#     instructions: |
#       Analyze the request and break it down...
#
# Example with agent (delegated to sub-agent):
#   - id: code
#     agent: coder
#     instructions: |
#       Implement the feature...
#
# WORKFLOW STRUCTURE
# ------------------
# This workflow implements the standard development cycle:
# 1. Plan - break down the task into discrete features
# 2. Implement - code and test each feature in a loop
# 3. Cleanup - finalize, run tests, and clean up
#
# =============================================================================

name: default
description: Standard development workflow with planning, implementation, and cleanup phases

agents:
  coder:
    description: Implements features and writes code
    tools:
      - Read
      - Write
      - Edit
      - Bash
      - Grep
      - Glob
    cannot:
      - commit without review
      - skip tests

  test-engineer:
    description: Writes and runs tests for implemented features
    tools:
      - Read
      - Write
      - Edit
      - Bash
    cannot:
      - modify feature code
      - skip test execution

  code-reviewer:
    description: Reviews code quality and provides feedback
    tools:
      - Read
      - Grep
      - Glob
    cannot:
      - modify code directly
      - approve own code

loops:
  implement:
    - id: code
      agent: coder
      instructions: |
        Implement feature: {task.title}

        1. Read relevant files to understand context
        2. Plan the implementation
        3. Write/edit code
        4. Verify it compiles
      on_fail: retry

    - id: test
      agent: test-engineer
      instructions: |
        Write tests for feature: {task.title}

        1. Create test cases based on acceptance criteria
        2. Implement tests
        3. Run tests and verify they pass
      on_fail: retry

    - id: review
      agent: code-reviewer
      instructions: |
        Review implementation of: {task.title}

        1. Check code quality and patterns
        2. Verify test coverage
        3. Provide feedback or approve
      on_fail: skip

steps:
  - id: plan
    type: action
    instructions: |
      Analyze the user's request and break it down into discrete features.

      For each feature, identify:
      - A unique ID
      - A clear title
      - Acceptance criteria

      Then call workflow_set_tasks with the features as tasks.

  - id: implement
    type: loop
    agent: coder

  - id: cleanup
    type: action
    instructions: |
      Finalize the implementation:

      1. Run all tests one final time
      2. Update any documentation
      3. Clean up any temporary files
      4. Summarize what was accomplished
